<?php

namespace Keyojel\Chart\Util;

trait Constants
{
    protected $customCookies = null;
    private static $categoryLabels = [
        'libxml'   => 'libxml',
        'openssl'  => 'OpenSSL',
        'pcre'     => 'PCRE',
        'sqlite3'  => 'SQLite3',
        'curl'     => 'cURL',
        'dom'      => 'DOM',
        'ftp'      => 'FTP',
        'gd'       => 'GD',
        'gmp'      => 'GMP',
        'iconv'    => 'iconv',
        'json'     => 'JSON',
        'ldap'     => 'LDAP',
        'mbstring' => 'mbstring',
        'odbc'     => 'ODBC',
        'pcntl'    => 'PCNTL',
        'pgsql'    => 'pgsql',
        'posix'    => 'POSIX',
        'mysqli'   => 'mysqli',
        'soap'     => 'SOAP',
        'exif'     => 'EXIF',
        'sysvmsg'  => 'sysvmsg',
        'xml'      => 'XML',
        'xsl'      => 'XSL',
    ];

    public $cp1252_map = array(
        "\xc2\x80" => "\xe2\x82\xac", /* EURO SIGN */
        "\xc2\x82" => "\xe2\x80\x9a", /* SINGLE LOW-9 QUOTATION MARK */
        "\xc2\x83" => "\xc6\x92", /* LATIN SMALL LETTER F WITH HOOK */
        "\xc2\x84" => "\xe2\x80\x9e", /* DOUBLE LOW-9 QUOTATION MARK */
        "\xc2\x85" => "\xe2\x80\xa6", /* HORIZONTAL ELLIPSIS */
        "\xc2\x86" => "\xe2\x80\xa0", /* DAGGER */
        "\xc2\x87" => "\xe2\x80\xa1", /* DOUBLE DAGGER */
        "\xc2\x88" => "\xcb\x86", /* MODIFIER LETTER CIRCUMFLEX ACCENT */
        "\xc2\x89" => "\xe2\x80\xb0", /* PER MILLE SIGN */
        "\xc2\x8a" => "\xc5\xa0", /* LATIN CAPITAL LETTER S WITH CARON */
        "\xc2\x8b" => "\xe2\x80\xb9", /* SINGLE LEFT-POINTING ANGLE QUOTATION */
        "\xc2\x8c" => "\xc5\x92", /* LATIN CAPITAL LIGATURE OE */
        "\xc2\x8e" => "\xc5\xbd", /* LATIN CAPITAL LETTER Z WITH CARON */
        "\xc2\x91" => "\xe2\x80\x98", /* LEFT SINGLE QUOTATION MARK */
        "\xc2\x92" => "\xe2\x80\x99", /* RIGHT SINGLE QUOTATION MARK */
        "\xc2\x93" => "\xe2\x80\x9c", /* LEFT DOUBLE QUOTATION MARK */
        "\xc2\x94" => "\xe2\x80\x9d", /* RIGHT DOUBLE QUOTATION MARK */
        "\xc2\x95" => "\xe2\x80\xa2", /* BULLET */
        "\xc2\x96" => "\xe2\x80\x93", /* EN DASH */
        "\xc2\x97" => "\xe2\x80\x94", /* EM DASH */

        "\xc2\x98" => "\xcb\x9c", /* SMALL TILDE */
        "\xc2\x99" => "\xe2\x84\xa2", /* TRADE MARK SIGN */
        "\xc2\x9a" => "\xc5\xa1", /* LATIN SMALL LETTER S WITH CARON */
        "\xc2\x9b" => "\xe2\x80\xba", /* SINGLE RIGHT-POINTING ANGLE QUOTATION*/
        "\xc2\x9c" => "\xc5\x93", /* LATIN SMALL LIGATURE OE */
        "\xc2\x9e" => "\xc5\xbe", /* LATIN SMALL LETTER Z WITH CARON */
        "\xc2\x9f" => "\xc5\xb8" /* LATIN CAPITAL LETTER Y WITH DIAERESIS*/
    );

    public $sign_map = [
        "\xc2\x80" => "\xe2\x82\xac", // EURO SIGN
        "\xc2\x82" => "\xe2\x80\x9a", // SINGLE LOW-9 QUOTATION MARK
        "\xc2\x83" => "\xc6\x92", // LATIN SMALL LETTER F WITH HOOK
        "\xc2\x84" => "\xe2\x80\x9e", // DOUBLE LOW-9 QUOTATION MARK
        "\xc2\x85" => "\xe2\x80\xa6", // HORIZONTAL ELLIPSIS
        "\xc2\x86" => "\xe2\x80\xa0", // DAGGER
        "\xc2\x87" => "\xe2\x80\xa1", // DOUBLE DAGGER
        "\xc2\x88" => "\xcb\x86", // MODIFIER LETTER CIRCUMFLEX ACCENT
        "\xc2\x89" => "\xe2\x80\xb0", // PER MILLE SIGN
        "\xc2\x8a" => "\xc5\xa0", // LATIN CAPITAL LETTER S WITH CARON
        "\xc2\x8b" => "\xe2\x80\xb9", // SINGLE LEFT-POINTING ANGLE QUOTE
        "\xc2\x8c" => "\xc5\x92", // LATIN CAPITAL LIGATURE OE
        "\xc2\x8e" => "\xc5\xbd", // LATIN CAPITAL LETTER Z WITH CARON
        "\xc2\x91" => "\xe2\x80\x98", // LEFT SINGLE QUOTATION MARK
        "\xc2\x92" => "\xe2\x80\x99", // RIGHT SINGLE QUOTATION MARK
        "\xc2\x93" => "\xe2\x80\x9c", // LEFT DOUBLE QUOTATION MARK
        "\xc2\x94" => "\xe2\x80\x9d", // RIGHT DOUBLE QUOTATION MARK
        "\xc2\x95" => "\xe2\x80\xa2", // BULLET
        "\xc2\x96" => "\xe2\x80\x93", // EN DASH
        "\xc2\x97" => "\xe2\x80\x94", // EM DASH
        "\xc2\x98" => "\xcb\x9c", // SMALL TILDE
        "\xc2\x99" => "\xe2\x84\xa2", // TRADE MARK SIGN
        "\xc2\x9a" => "\xc5\xa1", // LATIN SMALL LETTER S WITH CARON
        "\xc2\x9b" => "\xe2\x80\xba", // SINGLE RIGHT-POINTING ANGLE QUOTE
        "\xc2\x9c" => "\xc5\x93", // LATIN SMALL LIGATURE OE
        "\xc2\x9e" => "\xc5\xbe", // LATIN SMALL LETTER Z WITH CARON
        "\xc2\x9f" => "\xc5\xb8", // LATIN CAPITAL LETTER Y WITH DIAERESIS
        'Ã¼'       => 'ü',
        'Ã¤'       => 'ä',
        'Ã¶'       => 'ö',
        'Ã–'       => 'Ö',
        'ÃŸ'       => 'ß',
        'Ã '       => 'à',
        'Ã¡'       => 'á',
        'Ã¢'       => 'â',
        'Ã£'       => 'ã',
        'Ã¹'       => 'ù',
        'Ãº'       => 'ú',
        'Ã»'       => 'û',
        'Ã™'       => 'Ù',
        'Ãš'       => 'Ú',
        'Ã›'       => 'Û',
        'Ãœ'       => 'Ü',
        'Ã²'       => 'ò',
        'Ã³'       => 'ó',
        'Ã´'       => 'ô',
        'Ã¨'       => 'è',
        'Ã©'       => 'é',
        'Ãª'       => 'ê',
        'Ã«'       => 'ë',
        'Ã€'       => 'À',
        'Ã'       => 'Á',
        'Ã‚'       => 'Â',
        'Ãƒ'       => 'Ã',
        'Ã„'       => 'Ä',
        'Ã…'       => 'Å',
        'Ã‡'       => 'Ç',
        'Ãˆ'       => 'È',
        'Ã‰'       => 'É',
        'ÃŠ'       => 'Ê',
        'Ã‹'       => 'Ë',
        'ÃŒ'       => 'Ì',
        'Ã'       => 'Í',
        'ÃŽ'       => 'Î',
        'Ã'       => 'Ï',
        'Ã‘'       => 'Ñ',
        'Ã’'       => 'Ò',
        'Ã“'       => 'Ó',
        'Ã”'       => 'Ô',
        'Ã•'       => 'Õ',
        'Ã˜'       => 'Ø',
        'Ã¥'       => 'å',
        'Ã¦'       => 'æ',
        'Ã§'       => 'ç',
        'Ã¬'       => 'ì',
        'Ã­'       => 'í',
        'Ã®'       => 'î',
        'Ã¯'       => 'ï',
        'Ã°'       => 'ð',
        'Ã±'       => 'ñ',
        'Ãµ'       => 'õ',
        'Ã¸'       => 'ø',
        'Ã½'       => 'ý',
        'Ã¿'       => 'ÿ',
        'â‚¬'      => '€',
        'â€™'      => '’',
    ];

    public $char_a_map = [
        0x80 => "\xe2\x82\xac", # €
        0x82 => "\xe2\x80\x9a", # ‚
        0x83 => "\xc6\x92",     # ƒ
        0x84 => "\xe2\x80\x9e", # „
        0x85 => "\xe2\x80\xa6", # …
        0x86 => "\xe2\x80\xa0", # †
        0x87 => "\xe2\x80\xa1", # ‡
        0x88 => "\xcb\x86",     # ˆ
        0x89 => "\xe2\x80\xb0", # ‰
        0x8a => "\xc5\xa0",     # Š
        0x8b => "\xe2\x80\xb9", # ‹
        0x8c => "\xc5\x92",     # Œ
        0x8e => "\xc5\xbd",     # Ž
        0x91 => "\xe2\x80\x98", # ‘
        0x92 => "\xe2\x80\x99", # ’
        0x93 => "\xe2\x80\x9c", # “
        0x94 => "\xe2\x80\x9d", # ”
        0x95 => "\xe2\x80\xa2", # •
        0x96 => "\xe2\x80\x93", # –
        0x97 => "\xe2\x80\x94", # —
        0x98 => "\xcb\x9c",     # ˜
        0x99 => "\xe2\x84\xa2", # ™
        0x9a => "\xc5\xa1",     # š
        0x9b => "\xe2\x80\xba", # ›
        0x9c => "\xc5\x93",     # œ
        0x9e => "\xc5\xbe",     # ž
        0x9f => "\xc5\xb8",     # Ÿ
        0xa0 => "\xc2\xa0",     #
        0xa1 => "\xc2\xa1",     # ¡
        0xa2 => "\xc2\xa2",     # ¢
        0xa3 => "\xc2\xa3",     # £
        0xa4 => "\xc2\xa4",     # ¤
        0xa5 => "\xc2\xa5",     # ¥
        0xa6 => "\xc2\xa6",     # ¦
        0xa7 => "\xc2\xa7",     # §
        0xa8 => "\xc2\xa8",     # ¨
        0xa9 => "\xc2\xa9",     # ©
        0xaa => "\xc2\xaa",     # ª
        0xab => "\xc2\xab",     # «
        0xac => "\xc2\xac",     # ¬
        0xad => "\xc2\xad",     # ­
        0xae => "\xc2\xae",     # ®
        0xaf => "\xc2\xaf",     # ¯
        0xb0 => "\xc2\xb0",     # °
        0xb1 => "\xc2\xb1",     # ±
        0xb2 => "\xc2\xb2",     # ²
        0xb3 => "\xc2\xb3",     # ³
        0xb4 => "\xc2\xb4",     # ´
        0xb5 => "\xc2\xb5",     # µ
        0xb6 => "\xc2\xb6",     # ¶
        0xb7 => "\xc2\xb7",     # ·
        0xb8 => "\xc2\xb8",     # ¸
        0xb9 => "\xc2\xb9",     # ¹
        0xba => "\xc2\xba",     # º
        0xbb => "\xc2\xbb",     # »
        0xbc => "\xc2\xbc",     # ¼
        0xbd => "\xc2\xbd",     # ½
        0xbe => "\xc2\xbe",     # ¾
        0xbf => "\xc2\xbf",     # ¿
        0xc0 => "\xc3\x80",     # À
        0xc1 => "\xc3\x81",     # Á
        0xc2 => "\xc3\x82",     # Â
        0xc3 => "\xc3\x83",     # Ã
        0xc4 => "\xc3\x84",     # Ä
        0xc5 => "\xc3\x85",     # Å
        0xc6 => "\xc3\x86",     # Æ
        0xc7 => "\xc3\x87",     # Ç
        0xc8 => "\xc3\x88",     # È
        0xc9 => "\xc3\x89",     # É
        0xca => "\xc3\x8a",     # Ê
        0xcb => "\xc3\x8b",     # Ë
        0xcc => "\xc3\x8c",     # Ì
        0xcd => "\xc3\x8d",     # Í
        0xce => "\xc3\x8e",     # Î
        0xcf => "\xc3\x8f",     # Ï
        0xd0 => "\xc3\x90",     # Ð
        0xd1 => "\xc3\x91",     # Ñ
        0xd2 => "\xc3\x92",     # Ò
        0xd3 => "\xc3\x93",     # Ó
        0xd4 => "\xc3\x94",     # Ô
        0xd5 => "\xc3\x95",     # Õ
        0xd6 => "\xc3\x96",     # Ö
        0xd7 => "\xc3\x97",     # ×
        0xd8 => "\xc3\x98",     # Ø
        0xd9 => "\xc3\x99",     # Ù
        0xda => "\xc3\x9a",     # Ú
        0xdb => "\xc3\x9b",     # Û
        0xdc => "\xc3\x9c",     # Ü
        0xdd => "\xc3\x9d",     # Ý
        0xde => "\xc3\x9e",     # Þ
        0xdf => "\xc3\x9f",     # ß
        0xe0 => "\xc3\xa0",     # à
        0xe1 => "\xa1",         # á
        0xe2 => "\xc3\xa2",     # â
        0xe3 => "\xc3\xa3",     # ã
        0xe4 => "\xc3\xa4",     # ä
        0xe5 => "\xc3\xa5",     # å
        0xe6 => "\xc3\xa6",     # æ
        0xe7 => "\xc3\xa7",     # ç
        0xe8 => "\xc3\xa8",     # è
        0xe9 => "\xc3\xa9",     # é
        0xea => "\xc3\xaa",     # ê
        0xeb => "\xc3\xab",     # ë
        0xec => "\xc3\xac",     # ì
        0xed => "\xc3\xad",     # í
        0xee => "\xc3\xae",     # î
        0xef => "\xc3\xaf",     # ï
        0xf0 => "\xc3\xb0",     # ð
        0xf1 => "\xc3\xb1",     # ñ
        0xf2 => "\xc3\xb2",     # ò
        0xf3 => "\xc3\xb3",     # ó
        0xf4 => "\xc3\xb4",     # ô
        0xf5 => "\xc3\xb5",     # õ
        0xf6 => "\xc3\xb6",     # ö
        0xf7 => "\xc3\xb7",     # ÷
        0xf8 => "\xc3\xb8",     # ø
        0xf9 => "\xc3\xb9",     # ù
        0xfa => "\xc3\xba",     # ú
        0xfb => "\xc3\xbb",     # û
        0xfc => "\xc3\xbc",     # ü
        0xfd => "\xc3\xbd",     # ý
        0xfe => "\xc3\xbe",     # þ
    ];

    public $alpha_map = [
        "\x61",
        "\x62",
        "\x63",
        "\x64",
        "\x65",
        "\x66",
        "\x67",
        "\x68",
        "\x69",
        "\x6a",
        "\x6b",
        "\x6c",
        "\x6d",
        "\x6e",
        "\x6f",
        "\x70",
        "\x71",
        "\x72",
        "\x73",
        "\x74",
        "\x75",
        "\x76",
        "\x77",
        "\x78",
        "\x79",
        "\x7a",
    ];

    public $apn_map = array(
        "\t" => '&Tab;',
        "\n" => '&NewLine;',
        '!'  => '&excl;',
        '"'  => '&quot;',
        '#'  => '&num;',
        '$'  => '&dollar;',
        '%'  => '&percnt;',
        '&'  => '&amp;',
        "'"  => '&apos;',
        '('  => '&lpar;',
        ')'  => '&rpar;',
        '*'  => '&ast;',
        ''  => '&plus;',
        ','  => '&comma;',
        '.'  => '&period;',
        '/'  => '&sol;',
        ':'  => '&colon;',
        ';'  => '&semi;',
        '<'  => '&lt;',
        '<⃒' => '&nvlt;',
        '='  => '&equals;',
        '=⃥' => '&bne;',
        '>'  => '&gt;',
        '>⃒' => '&nvgt',
        '?'  => '&quest;',
        '@'  => '&commat;',
        '['  => '&lbrack;',
        ']'  => '&rsqb;',
        '^'  => '&Hat;',
        '_'  => '&lowbar;',
        '`'  => '&grave;',
        'fj' => '&fjlig;',
        '{'  => '&lbrace;',
        '|'  => '&vert;',
        '}'  => '&rcub;',
        ' '  => '&nbsp;',
        '¡'  => '&iexcl;',
        '¢'  => '&cent;',
        '£'  => '&pound;',
        '¤'  => '&curren;',
        '¥'  => '&yen;',
        '¦'  => '&brvbar;',
        '§'  => '&sect;',
        '¨'  => '&DoubleDot;',
        '©'  => '&copy;',
        'ª'  => '&ordf;',
        '«'  => '&laquo;',
        '¬'  => '&not;',
        '­'  => '&shy;',
        '®'  => '&reg;',
        '¯'  => '&macr;',
        '°'  => '&deg;',
        '±'  => '&plusmn;',
        '²'  => '&sup2;',
        '³'  => '&sup3;',
        '´'  => '&DiacriticalAcute;',
        'µ'  => '&micro;',
        '¶'  => '&para;',
        '·'  => '&CenterDot;',
        '¸'  => '&Cedilla;',
        '¹'  => '&sup1;',
        'º'  => '&ordm;',
        '»'  => '&raquo;',
        '¼'  => '&frac14;',
        '½'  => '&half;',
        '¾'  => '&frac34;',
        '¿'  => '&iquest;',
        'À'  => '&Agrave;',
        'Á'  => '&Aacute;',
        'Â'  => '&Acirc;',
        'Ã'  => '&Atilde;',
        'Ä'  => '&Auml;',
        'Å'  => '&Aring;',
        'Æ'  => '&AElig;',
        'Ç'  => '&Ccedil;',
        'È'  => '&Egrave;',
        'É'  => '&Eacute;',
        'Ê'  => '&Ecirc;',
        'Ë'  => '&Euml;',
        'Ì'  => '&Igrave;',
        'Í'  => '&Iacute;',
        'Î'  => '&Icirc;',
        'Ï'  => '&Iuml;',
        'Ð'  => '&ETH;',
        'Ñ'  => '&Ntilde;',
        'Ò'  => '&Ograve;',
        'Ó'  => '&Oacute;',
        'Ô'  => '&Ocirc;',
        'Õ'  => '&Otilde;',
        'Ö'  => '&Ouml;',
        '×'  => '&times;',
        'Ø'  => '&Oslash;',
        'Ù'  => '&Ugrave;',
        'Ú'  => '&Uacute;',
        'Û'  => '&Ucirc;',
        'Ü'  => '&Uuml;',
        'Ý'  => '&Yacute;',
        'Þ'  => '&THORN;',
        'ß'  => '&szlig;',
        'à'  => '&agrave;',
        'á'  => '&aacute;',
        'â'  => '&acirc;',
        'ã'  => '&atilde;',
        'ä'  => '&auml;',
        'å'  => '&aring;',
        'æ'  => '&aelig;',
        'ç'  => '&ccedil;',
        'è'  => '&egrave;',
        'é'  => '&eacute;',
        'ê'  => '&ecirc;',
        'ë'  => '&euml;',
        'ì'  => '&igrave;',
        'í'  => '&iacute;',
        'î'  => '&icirc;',
        'ï'  => '&iuml;',
        'ð'  => '&eth;',
        'ñ'  => '&ntilde;',
        'ò'  => '&ograve;',
        'ó'  => '&oacute;',
        'ô'  => '&ocirc;',
        'õ'  => '&otilde;',
        'ö'  => '&ouml;',
        '÷'  => '&divide;',
        'ø'  => '&oslash;',
        'ù'  => '&ugrave;',
        'ú'  => '&uacute;',
        'û'  => '&ucirc;',
        'ü'  => '&uuml;',
        'ý'  => '&yacute;',
        'þ'  => '&thorn;',
        'ÿ'  => '&yuml;',
        'Ā'  => '&Amacr;',
        'ā'  => '&amacr;',
        'Ă'  => '&Abreve;',
        'ă'  => '&abreve;',
        'Ą'  => '&Aogon;',
        'ą'  => '&aogon;',
        'Ć'  => '&Cacute;',
        'ć'  => '&cacute;',
        'Ĉ'  => '&Ccirc;',
        'ĉ'  => '&ccirc;',
        'Ċ'  => '&Cdot;',
        'ċ'  => '&cdot;',
        'Č'  => '&Ccaron;',
        'č'  => '&ccaron;',
        'Ď'  => '&Dcaron;',
        'ď'  => '&dcaron;',
        'Đ'  => '&Dstrok;',
        'đ'  => '&dstrok;',
        'Ē'  => '&Emacr;',
        'ē'  => '&emacr;',
        'Ė'  => '&Edot;',
        'ė'  => '&edot;',
        'Ę'  => '&Eogon;',
        'ę'  => '&eogon;',
        'Ě'  => '&Ecaron;',
        'ě'  => '&ecaron;',
        'Ĝ'  => '&Gcirc;',
        'ĝ'  => '&gcirc;',
        'Ğ'  => '&Gbreve;',
        'ğ'  => '&gbreve;',
        'Ġ'  => '&Gdot;',
        'ġ'  => '&gdot;',
        'Ģ'  => '&Gcedil;',
        'Ĥ'  => '&Hcirc;',
        'ĥ'  => '&hcirc;',
        'Ħ'  => '&Hstrok;',
        'ħ'  => '&hstrok;',
        'Ĩ'  => '&Itilde;',
        'ĩ'  => '&itilde;',
        'Ī'  => '&Imacr;',
        'ī'  => '&imacr;',
        'Į'  => '&Iogon;',
        'į'  => '&iogon;',
        'İ'  => '&Idot;',
        'ı'  => '&inodot;',
        'Ĳ'  => '&IJlig;',
        'ĳ'  => '&ijlig;',
        'Ĵ'  => '&Jcirc;',
        'ĵ'  => '&jcirc;',
        'Ķ'  => '&Kcedil;',
        'ķ'  => '&kcedil;',
        'ĸ'  => '&kgreen;',
        'Ĺ'  => '&Lacute;',
        'ĺ'  => '&lacute;',
        'Ļ'  => '&Lcedil;',
        'ļ'  => '&lcedil;',
        'Ľ'  => '&Lcaron;',
        'ľ'  => '&lcaron;',
        'Ŀ'  => '&Lmidot;',
        'ŀ'  => '&lmidot;',
        'Ł'  => '&Lstrok;',
        'ł'  => '&lstrok;',
        'Ń'  => '&Nacute;',
        'ń'  => '&nacute;',
        'Ņ'  => '&Ncedil;',
        'ņ'  => '&ncedil;',
        'Ň'  => '&Ncaron;',
        'ň'  => '&ncaron;',
        'ŉ'  => '&napos;',
        'Ŋ'  => '&ENG;',
        'ŋ'  => '&eng;',
        'Ō'  => '&Omacr;',
        'ō'  => '&omacr;',
        'Ő'  => '&Odblac;',
        'ő'  => '&odblac;',
        'Œ'  => '&OElig;',
        'œ'  => '&oelig;',
        'Ŕ'  => '&Racute;',
        'ŕ'  => '&racute;',
        'Ŗ'  => '&Rcedil;',
        'ŗ'  => '&rcedil;',
        'Ř'  => '&Rcaron;',
        'ř'  => '&rcaron;',
        'Ś'  => '&Sacute;',
        'ś'  => '&sacute;',
        'Ŝ'  => '&Scirc;',
        'ŝ'  => '&scirc;',
        'Ş'  => '&Scedil;',
        'ş'  => '&scedil;',
        'Š'  => '&Scaron;',
        'š'  => '&scaron;',
        'Ţ'  => '&Tcedil;',
        'ţ'  => '&tcedil;',
        'Ť'  => '&Tcaron;',
        'ť'  => '&tcaron;',
        'Ŧ'  => '&Tstrok;',
        'ŧ'  => '&tstrok;',
        'Ũ'  => '&Utilde;',
        'ũ'  => '&utilde;',
        'Ū'  => '&Umacr;',
        'ū'  => '&umacr;',
        'Ŭ'  => '&Ubreve;',
        'ŭ'  => '&ubreve;',
        'Ů'  => '&Uring;',
        'ů'  => '&uring;',
        'Ű'  => '&Udblac;',
        'ű'  => '&udblac;',
        'Ų'  => '&Uogon;',
        'ų'  => '&uogon;',
        'Ŵ'  => '&Wcirc;',
        'ŵ'  => '&wcirc;',
        'Ŷ'  => '&Ycirc;',
        'ŷ'  => '&ycirc;',
        'Ÿ'  => '&Yuml;',
        'Ź'  => '&Zacute;',
        'ź'  => '&zacute;',
        'Ż'  => '&Zdot;',
        'ż'  => '&zdot;',
        'Ž'  => '&Zcaron;',
        'ž'  => '&zcaron;',
        'ƒ'  => '&fnof;',
        'Ƶ'  => '&imped;',
        'ǵ'  => '&gacute;',
        'ȷ'  => '&jmath;',
        'ˆ'  => '&circ;',
        'ˇ'  => '&Hacek;',
        '˘'  => '&Breve;',
        '˙'  => '&dot;',
        '˚'  => '&ring;',
        '˛'  => '&ogon;',
        '˜'  => '&DiacriticalTilde;',
        '˝'  => '&DiacriticalDoubleAcute;',
        '̑'  => '&DownBreve;',
        'Α'  => '&Alpha;',
        'Β'  => '&Beta;',
        'Γ'  => '&Gamma;',
        'Δ'  => '&Delta;',
        'Ε'  => '&Epsilon;',
        'Ζ'  => '&Zeta;',
        'Η'  => '&Eta;',
        'Θ'  => '&Theta;',
        'Ι'  => '&Iota;',
        'Κ'  => '&Kappa;',
        'Λ'  => '&Lambda;',
        'Μ'  => '&Mu;',
        'Ν'  => '&Nu;',
        'Ξ'  => '&Xi;',
        'Ο'  => '&Omicron;',
        'Π'  => '&Pi;',
        'Ρ'  => '&Rho;',
        'Σ'  => '&Sigma;',
        'Τ'  => '&Tau;',
        'Υ'  => '&Upsilon;',
        'Φ'  => '&Phi;',
        'Χ'  => '&Chi;',
        'Ψ'  => '&Psi;',
        'Ω'  => '&Omega;',
        'α'  => '&alpha;',
        'β'  => '&beta;',
        'γ'  => '&gamma;',
        'δ'  => '&delta;',
        'ε'  => '&epsi;',
        'ζ'  => '&zeta;',
        'η'  => '&eta;',
        'θ'  => '&theta;',
        'ι'  => '&iota;',
        'κ'  => '&kappa;',
        'λ'  => '&lambda;',
        'μ'  => '&mu;',
        'ν'  => '&nu;',
        'ξ'  => '&xi;',
        'ο'  => '&omicron;',
        'π'  => '&pi;',
        'ρ'  => '&rho;',
        'ς'  => '&sigmav;',
        'σ'  => '&sigma;',
        'τ'  => '&tau;',
        'υ'  => '&upsi;',
        'φ'  => '&phi;',
        'χ'  => '&chi;',
        'ψ'  => '&psi;',
        'ω'  => '&omega;',
        'ϑ'  => '&thetasym;',
        'ϒ'  => '&upsih;',
        'ϕ'  => '&straightphi;',
        'ϖ'  => '&piv;',
        'Ϝ'  => '&Gammad;',
        'ϝ'  => '&gammad;',
        'ϰ'  => '&varkappa;',
        'ϱ'  => '&rhov;',
        'ϵ'  => '&straightepsilon;',
        '϶'  => '&backepsilon;',
        'Ё'  => '&IOcy;',
        'Ђ'  => '&DJcy;',
        'Ѓ'  => '&GJcy;',
        'Є'  => '&Jukcy;',
        'Ѕ'  => '&DScy;',
        'І'  => '&Iukcy;',
        'Ї'  => '&YIcy;',
        'Ј'  => '&Jsercy;',
        'Љ'  => '&LJcy;',
        'Њ'  => '&NJcy;',
        'Ћ'  => '&TSHcy;',
        'Ќ'  => '&KJcy;',
        'Ў'  => '&Ubrcy;',
        'Џ'  => '&DZcy;',
        'А'  => '&Acy;',
        'Б'  => '&Bcy;',
        'В'  => '&Vcy;',
        'Г'  => '&Gcy;',
        'Д'  => '&Dcy;',
        'Е'  => '&IEcy;',
        'Ж'  => '&ZHcy;',
        'З'  => '&Zcy;',
        'И'  => '&Icy;',
        'Й'  => '&Jcy;',
        'К'  => '&Kcy;',
        'Л'  => '&Lcy;',
        'М'  => '&Mcy;',
        'Н'  => '&Ncy;',
        'О'  => '&Ocy;',
        'П'  => '&Pcy;',
        'Р'  => '&Rcy;',
        'С'  => '&Scy;',
        'Т'  => '&Tcy;',
        'У'  => '&Ucy;',
        'Ф'  => '&Fcy;',
        'Х'  => '&KHcy;',
        'Ц'  => '&TScy;',
        'Ч'  => '&CHcy;',
        'Ш'  => '&SHcy;',
        'Щ'  => '&SHCHcy;',
        'Ъ'  => '&HARDcy;',
        'Ы'  => '&Ycy;',
        'Ь'  => '&SOFTcy;',
        'Э'  => '&Ecy;',
        'Ю'  => '&YUcy;',
        'Я'  => '&YAcy;',
        'а'  => '&acy;',
        'б'  => '&bcy;',
        'в'  => '&vcy;',
        'г'  => '&gcy;',
        'д'  => '&dcy;',
        'е'  => '&iecy;',
        'ж'  => '&zhcy;',
        'з'  => '&zcy;',
        'и'  => '&icy;',
        'й'  => '&jcy;',
        'к'  => '&kcy;',
        'л'  => '&lcy;',
        'м'  => '&mcy;',
        'н'  => '&ncy;',
        'о'  => '&ocy;',
        'п'  => '&pcy;',
        'р'  => '&rcy;',
        'с'  => '&scy;',
        'т'  => '&tcy;',
        'у'  => '&ucy;',
        'ф'  => '&fcy;',
        'х'  => '&khcy;',
        'ц'  => '&tscy;',
        'ч'  => '&chcy;',
        'ш'  => '&shcy;',
        'щ'  => '&shchcy;',
        'ъ'  => '&hardcy;',
        'ы'  => '&ycy;',
        'ь'  => '&softcy;',
        'э'  => '&ecy;',
        'ю'  => '&yucy;',
        'я'  => '&yacy;',
        'ё'  => '&iocy;',
        'ђ'  => '&djcy;',
        'ѓ'  => '&gjcy;',
        'є'  => '&jukcy;',
        'ѕ'  => '&dscy;',
        'і'  => '&iukcy;',
        'ї'  => '&yicy;',
        'ј'  => '&jsercy;',
        'љ'  => '&ljcy;',
        'њ'  => '&njcy;',
        'ћ'  => '&tshcy;',
        'ќ'  => '&kjcy;',
        'ў'  => '&ubrcy;',
        'џ'  => '&dzcy;',
        ' '  => '&ensp;',
        ' '  => '&emsp;',
        ' '  => '&emsp13;',
        ' '  => '&emsp14;',
        ' '  => '&numsp;',
        ' '  => '&puncsp;',
        ' '  => '&ThinSpace;',
        ' '  => '&hairsp;',
        '​'  => '&ZeroWidthSpace;',
        '‌'  => '&zwnj;',
        '‍'  => '&zwj;',
        '‎'  => '&lrm;',
        '‏'  => '&rlm;',
        '‐'  => '&hyphen;',
        '–'  => '&ndash;',
        '—'  => '&mdash;',
        '―'  => '&horbar;',
        '‖'  => '&Verbar;',
        '‘'  => '&OpenCurlyQuote;',
        '’'  => '&rsquo;',
        '‚'  => '&sbquo;',
        '“'  => '&OpenCurlyDoubleQuote;',
        '”'  => '&rdquo;',
        '„'  => '&bdquo;',
        '†'  => '&dagger;',
        '‡'  => '&Dagger;',
        '•'  => '&bull;',
        '‥'  => '&nldr;',
        '…'  => '&hellip;',
        '‰'  => '&permil;',
        '‱'  => '&pertenk;',
        '′'  => '&prime;',
        '″'  => '&Prime;',
        '‴'  => '&tprime;',
        '‵'  => '&backprime;',
        '‹'  => '&lsaquo;',
        '›'  => '&rsaquo;',
        '‾'  => '&oline;',
        '⁁'  => '&caret;',
        '⁃'  => '&hybull;',
        '⁄'  => '&frasl;',
        '⁏'  => '&bsemi;',
        '⁗'  => '&qprime;',
        ' '  => '&MediumSpace;',
        '  ' => '&ThickSpace;',
        '⁠'  => '&NoBreak;',
        '⁡'  => '&af;',
        '⁢'  => '&InvisibleTimes;',
        '⁣'  => '&ic;',
        '€'  => '&euro;',
        '⃛'  => '&TripleDot;',
        '⃜'  => '&DotDot;',
        'ℂ'  => '&complexes;',
        '℅'  => '&incare;',
        'ℊ'  => '&gscr;',
        'ℋ'  => '&HilbertSpace;',
        'ℌ'  => '&Hfr;',
        'ℍ'  => '&Hopf;',
        'ℎ'  => '&planckh;',
        'ℏ'  => '&planck;',
        'ℐ'  => '&imagline;',
        'ℑ'  => '&Ifr;',
        'ℒ'  => '&lagran;',
        'ℓ'  => '&ell;',
        'ℕ'  => '&naturals;',
        '№'  => '&numero;',
        '℗'  => '&copysr;',
        '℘'  => '&wp;',
        'ℙ'  => '&primes;',
        'ℚ'  => '&rationals;',
        'ℛ'  => '&realine;',
        'ℜ'  => '&Rfr;',
        'ℝ'  => '&Ropf;',
        '℞'  => '&rx;',
        '™'  => '&trade;',
        'ℤ'  => '&Zopf;',
        '℧'  => '&mho;',
        'ℨ'  => '&Zfr;',
        '℩'  => '&iiota;',
        'ℬ'  => '&Bscr;',
        'ℭ'  => '&Cfr;',
        'ℯ'  => '&escr;',
        'ℰ'  => '&expectation;',
        'ℱ'  => '&Fouriertrf;',
        'ℳ'  => '&Mellintrf;',
        'ℴ'  => '&orderof;',
        'ℵ'  => '&aleph;',
        'ℶ'  => '&beth;',
        'ℷ'  => '&gimel;',
        'ℸ'  => '&daleth;',
        'ⅅ'  => '&CapitalDifferentialD;',
        'ⅆ'  => '&DifferentialD;',
        'ⅇ'  => '&exponentiale;',
        'ⅈ'  => '&ImaginaryI;',
        '⅓'  => '&frac13;',
        '⅔'  => '&frac23;',
        '⅕'  => '&frac15;',
        '⅖'  => '&frac25;',
        '⅗'  => '&frac35;',
        '⅘'  => '&frac45;',
        '⅙'  => '&frac16;',
        '⅚'  => '&frac56;',
        '⅛'  => '&frac18;',
        '⅜'  => '&frac38;',
        '⅝'  => '&frac58;',
        '⅞'  => '&frac78;',
        '←'  => '&larr;',
        '↑'  => '&uarr;',
        '→'  => '&srarr;',
        '↓'  => '&darr;',
        '↔'  => '&harr;',
        '↕'  => '&UpDownArrow;',
        '↖'  => '&nwarrow;',
        '↗'  => '&UpperRightArrow;',
        '↘'  => '&LowerRightArrow;',
        '↙'  => '&swarr;',
        '↚'  => '&nleftarrow;',
        '↛'  => '&nrarr;',
        '↝'  => '&rarrw;',
        '↝̸' => '&nrarrw;',
        '↞'  => '&Larr;',
        '↟'  => '&Uarr;',
        '↠'  => '&twoheadrightarrow;',
        '↡'  => '&Darr;',
        '↢'  => '&larrtl;',
        '↣'  => '&rarrtl;',
        '↤'  => '&LeftTeeArrow;',
        '↥'  => '&UpTeeArrow;',
        '↦'  => '&map;',
        '↧'  => '&DownTeeArrow;',
        '↩'  => '&larrhk;',
        '↪'  => '&rarrhk;',
        '↫'  => '&larrlp;',
        '↬'  => '&looparrowright;',
        '↭'  => '&harrw;',
        '↮'  => '&nleftrightarrow;',
        '↰'  => '&Lsh;',
        '↱'  => '&rsh;',
        '↲'  => '&ldsh;',
        '↳'  => '&rdsh;',
        '↵'  => '&crarr;',
        '↶'  => '&curvearrowleft;',
        '↷'  => '&curarr;',
        '↺'  => '&olarr;',
        '↻'  => '&orarr;',
        '↼'  => '&leftharpoonup;',
        '↽'  => '&leftharpoondown;',
        '↾'  => '&RightUpVector;',
        '↿'  => '&uharl;',
        '⇀'  => '&rharu;',
        '⇁'  => '&rhard;',
        '⇂'  => '&RightDownVector;',
        '⇃'  => '&dharl;',
        '⇄'  => '&rightleftarrows;',
        '⇅'  => '&udarr;',
        '⇆'  => '&lrarr;',
        '⇇'  => '&llarr;',
        '⇈'  => '&upuparrows;',
        '⇉'  => '&rrarr;',
        '⇊'  => '&downdownarrows;',
        '⇋'  => '&leftrightharpoons;',
        '⇌'  => '&rightleftharpoons;',
        '⇍'  => '&nLeftarrow;',
        '⇎'  => '&nhArr;',
        '⇏'  => '&nrArr;',
        '⇐'  => '&DoubleLeftArrow;',
        '⇑'  => '&DoubleUpArrow;',
        '⇒'  => '&Implies;',
        '⇓'  => '&Downarrow;',
        '⇔'  => '&hArr;',
        '⇕'  => '&Updownarrow;',
        '⇖'  => '&nwArr;',
        '⇗'  => '&neArr;',
        '⇘'  => '&seArr;',
        '⇙'  => '&swArr;',
        '⇚'  => '&lAarr;',
        '⇛'  => '&rAarr;',
        '⇝'  => '&zigrarr;',
        '⇤'  => '&LeftArrowBar;',
        '⇥'  => '&RightArrowBar;',
        '⇵'  => '&DownArrowUpArrow;',
        '⇽'  => '&loarr;',
        '⇾'  => '&roarr;',
        '⇿'  => '&hoarr;',
        '∀'  => '&forall;',
        '∁'  => '&comp;',
        '∂'  => '&part;',
        '∂̸' => '&npart;',
        '∃'  => '&Exists;',
        '∄'  => '&nexist;',
        '∅'  => '&empty;',
        '∇'  => '&nabla;',
        '∈'  => '&isinv;',
        '∉'  => '&notin;',
        '∋'  => '&ReverseElement;',
        '∌'  => '&notniva;',
        '∏'  => '&prod;',
        '∐'  => '&Coproduct;',
        '∑'  => '&sum;',
        '−'  => '&minus;',
        '∓'  => '&MinusPlus;',
        '∔'  => '&plusdo;',
        '∖'  => '&ssetmn;',
        '∗'  => '&lowast;',
        '∘'  => '&compfn;',
        '√'  => '&Sqrt;',
        '∝'  => '&prop;',
        '∞'  => '&infin;',
        '∟'  => '&angrt;',
        '∠'  => '&angle;',
        '∠⃒' => '&nang;',
        '∡'  => '&angmsd;',
        '∢'  => '&angsph;',
        '∣'  => '&mid;',
        '∤'  => '&nshortmid;',
        '∥'  => '&shortparallel;',
        '∦'  => '&nparallel;',
        '∧'  => '&and;',
        '∨'  => '&or;',
        '∩'  => '&cap;',
        '∩︀' => '&caps;',
        '∪'  => '&cup;',
        '∪︀' => '&cups',
        '∫'  => '&Integral;',
        '∬'  => '&Int;',
        '∭'  => '&tint;',
        '∮'  => '&ContourIntegral;',
        '∯'  => '&DoubleContourIntegral;',
        '∰'  => '&Cconint;',
        '∱'  => '&cwint;',
        '∲'  => '&cwconint;',
        '∳'  => '&awconint;',
        '∴'  => '&there4;',
        '∵'  => '&Because;',
        '∶'  => '&ratio;',
        '∷'  => '&Colon;',
        '∸'  => '&minusd;',
        '∺'  => '&mDDot;',
        '∻'  => '&homtht;',
        '∼'  => '&sim;',
        '∼⃒' => '&nvsim;',
        '∽'  => '&bsim;',
        '∽̱' => '&race;',
        '∾'  => '&ac;',
        '∾̳' => '&acE;',
        '∿'  => '&acd;',
        '≀'  => '&wr;',
        '≁'  => '&NotTilde;',
        '≂'  => '&esim;',
        '≂̸' => '&nesim;',
        '≃'  => '&simeq;',
        '≄'  => '&nsime;',
        '≅'  => '&TildeFullEqual;',
        '≆'  => '&simne;',
        '≇'  => '&ncong;',
        '≈'  => '&approx;',
        '≉'  => '&napprox;',
        '≊'  => '&ape;',
        '≋'  => '&apid;',
        '≋̸' => '&napid;',
        '≌'  => '&bcong;',
        '≍'  => '&CupCap;',
        '≍⃒' => '&nvap;',
        '≎'  => '&bump;',
        '≎̸' => '&nbump;',
        '≏'  => '&HumpEqual;',
        '≏̸' => '&nbumpe;',
        '≐'  => '&esdot;',
        '≐̸' => '&nedot;',
        '≑'  => '&doteqdot;',
        '≒'  => '&fallingdotseq;',
        '≓'  => '&risingdotseq;',
        '≔'  => '&coloneq;',
        '≕'  => '&eqcolon;',
        '≖'  => '&ecir;',
        '≗'  => '&circeq;',
        '≙'  => '&wedgeq;',
        '≚'  => '&veeeq;',
        '≜'  => '&triangleq;',
        '≟'  => '&equest;',
        '≠'  => '&NotEqual;',
        '≡'  => '&Congruent;',
        '≡⃥' => '&bnequiv;',
        '≢'  => '&NotCongruent;',
        '≤'  => '&leq;',
        '≤⃒' => '&nvle;',
        '≥'  => '&ge;',
        '≥⃒' => '&nvge;',
        '≦'  => '&lE;',
        '≦̸' => '&nlE;',
        '≧'  => '&geqq;',
        '≧̸' => '&NotGreaterFullEqual;',
        '≨'  => '&lneqq;',
        '≨︀' => '&lvertneqq;',
        '≩'  => '&gneqq;',
        '≩︀' => '&gvertneqq;',
        '≪'  => '&ll;',
        '≪̸' => '&nLtv;',
        '≪⃒' => '&nLt;',
        '≫'  => '&gg;',
        '≫̸' => '&NotGreaterGreater;',
        '≫⃒' => '&nGt;',
        '≬'  => '&between;',
        '≭'  => '&NotCupCap;',
        '≮'  => '&NotLess;',
        '≯'  => '&ngtr;',
        '≰'  => '&NotLessEqual;',
        '≱'  => '&ngeq;',
        '≲'  => '&LessTilde;',
        '≳'  => '&GreaterTilde;',
        '≴'  => '&nlsim;',
        '≵'  => '&ngsim;',
        '≶'  => '&lessgtr;',
        '≷'  => '&gl;',
        '≸'  => '&ntlg;',
        '≹'  => '&NotGreaterLess;',
        '≺'  => '&prec;',
        '≻'  => '&succ;',
        '≼'  => '&PrecedesSlantEqual;',
        '≽'  => '&succcurlyeq;',
        '≾'  => '&precsim;',
        '≿'  => '&SucceedsTilde;',
        '≿̸' => '&NotSucceedsTilde;',
        '⊀'  => '&npr;',
        '⊁'  => '&NotSucceeds;',
        '⊂'  => '&sub;',
        '⊂⃒' => '&vnsub;',
        '⊃'  => '&sup;',
        '⊃⃒' => '&nsupset;',
        '⊄'  => '&nsub;',
        '⊅'  => '&nsup;',
        '⊆'  => '&SubsetEqual;',
        '⊇'  => '&supe;',
        '⊈'  => '&NotSubsetEqual;',
        '⊉'  => '&NotSupersetEqual;',
        '⊊'  => '&subsetneq;',
        '⊊︀' => '&vsubne;',
        '⊋'  => '&supsetneq;',
        '⊋︀' => '&vsupne;',
        '⊍'  => '&cupdot;',
        '⊎'  => '&UnionPlus;',
        '⊏'  => '&sqsub;',
        '⊏̸' => '&NotSquareSubset;',
        '⊐'  => '&sqsupset;',
        '⊐̸' => '&NotSquareSuperset;',
        '⊑'  => '&SquareSubsetEqual;',
        '⊒'  => '&SquareSupersetEqual;',
        '⊓'  => '&sqcap;',
        '⊓︀' => '&sqcaps;',
        '⊔'  => '&sqcup;',
        '⊔︀' => '&sqcups;',
        '⊕'  => '&CirclePlus;',
        '⊖'  => '&ominus;',
        '⊗'  => '&CircleTimes;',
        '⊘'  => '&osol;',
        '⊙'  => '&CircleDot;',
        '⊚'  => '&ocir;',
        '⊛'  => '&oast;',
        '⊝'  => '&odash;',
        '⊞'  => '&boxplus;',
        '⊟'  => '&boxminus;',
        '⊠'  => '&timesb;',
        '⊡'  => '&sdotb;',
        '⊢'  => '&vdash;',
        '⊣'  => '&dashv;',
        '⊤'  => '&DownTee;',
        '⊥'  => '&perp;',
        '⊧'  => '&models;',
        '⊨'  => '&DoubleRightTee;',
        '⊩'  => '&Vdash;',
        '⊪'  => '&Vvdash;',
        '⊫'  => '&VDash;',
        '⊬'  => '&nvdash;',
        '⊭'  => '&nvDash;',
        '⊮'  => '&nVdash;',
        '⊯'  => '&nVDash;',
        '⊰'  => '&prurel;',
        '⊲'  => '&vartriangleleft;',
        '⊳'  => '&vrtri;',
        '⊴'  => '&LeftTriangleEqual;',
        '⊴⃒' => '&nvltrie;',
        '⊵'  => '&RightTriangleEqual;',
        '⊵⃒' => '&nvrtrie;',
        '⊶'  => '&origof;',
        '⊷'  => '&imof;',
        '⊸'  => '&mumap;',
        '⊹'  => '&hercon;',
        '⊺'  => '&intcal;',
        '⊻'  => '&veebar;',
        '⊽'  => '&barvee;',
        '⊾'  => '&angrtvb;',
        '⊿'  => '&lrtri;',
        '⋀'  => '&xwedge;',
        '⋁'  => '&xvee;',
        '⋂'  => '&bigcap;',
        '⋃'  => '&bigcup;',
        '⋄'  => '&diamond;',
        '⋅'  => '&sdot;',
        '⋆'  => '&Star;',
        '⋇'  => '&divonx;',
        '⋈'  => '&bowtie;',
        '⋉'  => '&ltimes;',
        '⋊'  => '&rtimes;',
        '⋋'  => '&lthree;',
        '⋌'  => '&rthree;',
        '⋍'  => '&backsimeq;',
        '⋎'  => '&curlyvee;',
        '⋏'  => '&curlywedge;',
        '⋐'  => '&Sub;',
        '⋑'  => '&Supset;',
        '⋒'  => '&Cap;',
        '⋓'  => '&Cup;',
        '⋔'  => '&pitchfork;',
        '⋕'  => '&epar;',
        '⋖'  => '&lessdot;',
        '⋗'  => '&gtrdot;',
        '⋘'  => '&Ll;',
        '⋘̸' => '&nLl;',
        '⋙'  => '&Gg;',
        '⋙̸' => '&nGg;',
        '⋚'  => '&lesseqgtr;',
        '⋚︀' => '&lesg;',
        '⋛'  => '&gtreqless;',
        '⋛︀' => '&gesl;',
        '⋞'  => '&curlyeqprec;',
        '⋟'  => '&cuesc;',
        '⋠'  => '&NotPrecedesSlantEqual;',
        '⋡'  => '&NotSucceedsSlantEqual;',
        '⋢'  => '&NotSquareSubsetEqual;',
        '⋣'  => '&NotSquareSupersetEqual;',
        '⋦'  => '&lnsim;',
        '⋧'  => '&gnsim;',
        '⋨'  => '&precnsim;',
        '⋩'  => '&scnsim;',
        '⋪'  => '&nltri;',
        '⋫'  => '&ntriangleright;',
        '⋬'  => '&nltrie;',
        '⋭'  => '&NotRightTriangleEqual;',
        '⋮'  => '&vellip;',
        '⋯'  => '&ctdot;',
        '⋰'  => '&utdot;',
        '⋱'  => '&dtdot;',
        '⋲'  => '&disin;',
        '⋳'  => '&isinsv;',
        '⋴'  => '&isins;',
        '⋵'  => '&isindot;',
        '⋵̸' => '&notindot;',
        '⋶'  => '&notinvc;',
        '⋷'  => '&notinvb;',
        '⋹'  => '&isinE;',
        '⋹̸' => '&notinE;',
        '⋺'  => '&nisd;',
        '⋻'  => '&xnis;',
        '⋼'  => '&nis;',
        '⋽'  => '&notnivc;',
        '⋾'  => '&notnivb;',
        '⌅'  => '&barwed;',
        '⌆'  => '&doublebarwedge;',
        '⌈'  => '&lceil;',
        '⌉'  => '&RightCeiling;',
        '⌊'  => '&LeftFloor;',
        '⌋'  => '&RightFloor;',
        '⌌'  => '&drcrop;',
        '⌍'  => '&dlcrop;',
        '⌎'  => '&urcrop;',
        '⌏'  => '&ulcrop;',
        '⌐'  => '&bnot;',
        '⌒'  => '&profline;',
        '⌓'  => '&profsurf;',
        '⌕'  => '&telrec;',
        '⌖'  => '&target;',
        '⌜'  => '&ulcorner;',
        '⌝'  => '&urcorner;',
        '⌞'  => '&llcorner;',
        '⌟'  => '&drcorn;',
        '⌢'  => '&frown;',
        '⌣'  => '&smile;',
        '⌭'  => '&cylcty;',
        '⌮'  => '&profalar;',
        '⌶'  => '&topbot;',
        '⌽'  => '&ovbar;',
        '⌿'  => '&solbar;',
        '⍼'  => '&angzarr;',
        '⎰'  => '&lmoust;',
        '⎱'  => '&rmoust;',
        '⎴'  => '&OverBracket;',
        '⎵'  => '&bbrk;',
        '⎶'  => '&bbrktbrk;',
        '⏜'  => '&OverParenthesis;',
        '⏝'  => '&UnderParenthesis;',
        '⏞'  => '&OverBrace;',
        '⏟'  => '&UnderBrace;',
        '⏢'  => '&trpezium;',
        '⏧'  => '&elinters;',
        '␣'  => '&blank;',
        'Ⓢ'  => '&oS;',
        '─'  => '&HorizontalLine;',
        '│'  => '&boxv;',
        '┌'  => '&boxdr;',
        '┐'  => '&boxdl;',
        '└'  => '&boxur;',
        '┘'  => '&boxul;',
        '├'  => '&boxvr;',
        '┤'  => '&boxvl;',
        '┬'  => '&boxhd;',
        '┴'  => '&boxhu;',
        '┼'  => '&boxvh;',
        '═'  => '&boxH;',
        '║'  => '&boxV;',
        '╒'  => '&boxdR;',
        '╓'  => '&boxDr;',
        '╔'  => '&boxDR;',
        '╕'  => '&boxdL;',
        '╖'  => '&boxDl;',
        '╗'  => '&boxDL;',
        '╘'  => '&boxuR;',
        '╙'  => '&boxUr;',
        '╚'  => '&boxUR;',
        '╛'  => '&boxuL;',
        '╜'  => '&boxUl;',
        '╝'  => '&boxUL;',
        '╞'  => '&boxvR;',
        '╟'  => '&boxVr;',
        '╠'  => '&boxVR;',
        '╡'  => '&boxvL;',
        '╢'  => '&boxVl;',
        '╣'  => '&boxVL;',
        '╤'  => '&boxHd;',
        '╥'  => '&boxhD;',
        '╦'  => '&boxHD;',
        '╧'  => '&boxHu;',
        '╨'  => '&boxhU;',
        '╩'  => '&boxHU;',
        '╪'  => '&boxvH;',
        '╫'  => '&boxVh;',
        '╬'  => '&boxVH;',
        '▀'  => '&uhblk;',
        '▄'  => '&lhblk;',
        '█'  => '&block;',
        '░'  => '&blk14;',
        '▒'  => '&blk12;',
        '▓'  => '&blk34;',
        '□'  => '&Square;',
        '▪'  => '&squarf;',
        '▫'  => '&EmptyVerySmallSquare;',
        '▭'  => '&rect;',
        '▮'  => '&marker;',
        '▱'  => '&fltns;',
        '△'  => '&bigtriangleup;',
        '▴'  => '&blacktriangle;',
        '▵'  => '&triangle;',
        '▸'  => '&blacktriangleright;',
        '▹'  => '&rtri;',
        '▽'  => '&bigtriangledown;',
        '▾'  => '&blacktriangledown;',
        '▿'  => '&triangledown;',
        '◂'  => '&blacktriangleleft;',
        '◃'  => '&ltri;',
        '◊'  => '&lozenge;',
        '○'  => '&cir;',
        '◬'  => '&tridot;',
        '◯'  => '&bigcirc;',
        '◸'  => '&ultri;',
        '◹'  => '&urtri;',
        '◺'  => '&lltri;',
        '◻'  => '&EmptySmallSquare;',
        '◼'  => '&FilledSmallSquare;',
        '★'  => '&starf;',
        '☆'  => '&star;',
        '☎'  => '&phone;',
        '♀'  => '&female;',
        '♂'  => '&male;',
        '♠'  => '&spadesuit;',
        '♣'  => '&clubs;',
        '♥'  => '&hearts;',
        '♦'  => '&diamondsuit;',
        '♪'  => '&sung;',
        '♭'  => '&flat;',
        '♮'  => '&natur;',
        '♯'  => '&sharp;',
        '✓'  => '&check;',
        '✗'  => '&cross;',
        '✠'  => '&maltese;',
        '✶'  => '&sext;',
        '❘'  => '&VerticalSeparator;',
        '❲'  => '&lbbrk;',
        '❳'  => '&rbbrk;',
        '⟈'  => '&bsolhsub;',
        '⟉'  => '&suphsol;',
        '⟦'  => '&LeftDoubleBracket;',
        '⟧'  => '&RightDoubleBracket;',
        '⟨'  => '&langle;',
        '⟩'  => '&RightAngleBracket;',
        '⟪'  => '&Lang;',
        '⟫'  => '&Rang;',
        '⟬'  => '&loang;',
        '⟭'  => '&roang;',
        '⟵'  => '&longleftarrow;',
        '⟶'  => '&LongRightArrow;',
        '⟷'  => '&LongLeftRightArrow;',
        '⟸'  => '&xlArr;',
        '⟹'  => '&DoubleLongRightArrow;',
        '⟺'  => '&xhArr;',
        '⟼'  => '&xmap;',
        '⟿'  => '&dzigrarr;',
        '⤂'  => '&nvlArr;',
        '⤃'  => '&nvrArr;',
        '⤄'  => '&nvHarr;',
        '⤅'  => '&Map;',
        '⤌'  => '&lbarr;',
        '⤍'  => '&bkarow;',
        '⤎'  => '&lBarr;',
        '⤏'  => '&dbkarow;',
        '⤐'  => '&drbkarow;',
        '⤑'  => '&DDotrahd;',
        '⤒'  => '&UpArrowBar;',
        '⤓'  => '&DownArrowBar;',
        '⤖'  => '&Rarrtl;',
        '⤙'  => '&latail;',
        '⤚'  => '&ratail;',
        '⤛'  => '&lAtail;',
        '⤜'  => '&rAtail;',
        '⤝'  => '&larrfs;',
        '⤞'  => '&rarrfs;',
        '⤟'  => '&larrbfs;',
        '⤠'  => '&rarrbfs;',
        '⤣'  => '&nwarhk;',
        '⤤'  => '&nearhk;',
        '⤥'  => '&searhk;',
        '⤦'  => '&swarhk;',
        '⤧'  => '&nwnear;',
        '⤨'  => '&toea;',
        '⤩'  => '&seswar;',
        '⤪'  => '&swnwar;',
        '⤳'  => '&rarrc;',
        '⤳̸' => '&nrarrc;',
        '⤵'  => '&cudarrr;',
        '⤶'  => '&ldca;',
        '⤷'  => '&rdca;',
        '⤸'  => '&cudarrl;',
        '⤹'  => '&larrpl;',
        '⤼'  => '&curarrm;',
        '⤽'  => '&cularrp;',
        '⥅'  => '&rarrpl;',
        '⥈'  => '&harrcir;',
        '⥉'  => '&Uarrocir;',
        '⥊'  => '&lurdshar;',
        '⥋'  => '&ldrushar;',
        '⥎'  => '&LeftRightVector;',
        '⥏'  => '&RightUpDownVector;',
        '⥐'  => '&DownLeftRightVector;',
        '⥑'  => '&LeftUpDownVector;',
        '⥒'  => '&LeftVectorBar;',
        '⥓'  => '&RightVectorBar;',
        '⥔'  => '&RightUpVectorBar;',
        '⥕'  => '&RightDownVectorBar;',
        '⥖'  => '&DownLeftVectorBar;',
        '⥗'  => '&DownRightVectorBar;',
        '⥘'  => '&LeftUpVectorBar;',
        '⥙'  => '&LeftDownVectorBar;',
        '⥚'  => '&LeftTeeVector;',
        '⥛'  => '&RightTeeVector;',
        '⥜'  => '&RightUpTeeVector;',
        '⥝'  => '&RightDownTeeVector;',
        '⥞'  => '&DownLeftTeeVector;',
        '⥟'  => '&DownRightTeeVector;',
        '⥠'  => '&LeftUpTeeVector;',
        '⥡'  => '&LeftDownTeeVector;',
        '⥢'  => '&lHar;',
        '⥣'  => '&uHar;',
        '⥤'  => '&rHar;',
        '⥥'  => '&dHar;',
        '⥦'  => '&luruhar;',
        '⥧'  => '&ldrdhar;',
        '⥨'  => '&ruluhar;',
        '⥩'  => '&rdldhar;',
        '⥪'  => '&lharul;',
        '⥫'  => '&llhard;',
        '⥬'  => '&rharul;',
        '⥭'  => '&lrhard;',
        '⥮'  => '&udhar;',
        '⥯'  => '&ReverseUpEquilibrium;',
        '⥰'  => '&RoundImplies;',
        '⥱'  => '&erarr;',
        '⥲'  => '&simrarr;',
        '⥳'  => '&larrsim;',
        '⥴'  => '&rarrsim;',
        '⥵'  => '&rarrap;',
        '⥶'  => '&ltlarr;',
        '⥸'  => '&gtrarr;',
        '⥹'  => '&subrarr;',
        '⥻'  => '&suplarr;',
        '⥼'  => '&lfisht;',
        '⥽'  => '&rfisht;',
        '⥾'  => '&ufisht;',
        '⥿'  => '&dfisht;',
        '⦅'  => '&lopar;',
        '⦆'  => '&ropar;',
        '⦋'  => '&lbrke;',
        '⦌'  => '&rbrke;',
        '⦍'  => '&lbrkslu;',
        '⦎'  => '&rbrksld;',
        '⦏'  => '&lbrksld;',
        '⦐'  => '&rbrkslu;',
        '⦑'  => '&langd;',
        '⦒'  => '&rangd;',
        '⦓'  => '&lparlt;',
        '⦔'  => '&rpargt;',
        '⦕'  => '&gtlPar;',
        '⦖'  => '&ltrPar;',
        '⦚'  => '&vzigzag;',
        '⦜'  => '&vangrt;',
        '⦝'  => '&angrtvbd;',
        '⦤'  => '&ange;',
        '⦥'  => '&range;',
        '⦦'  => '&dwangle;',
        '⦧'  => '&uwangle;',
        '⦨'  => '&angmsdaa;',
        '⦩'  => '&angmsdab;',
        '⦪'  => '&angmsdac;',
        '⦫'  => '&angmsdad;',
        '⦬'  => '&angmsdae;',
        '⦭'  => '&angmsdaf;',
        '⦮'  => '&angmsdag;',
        '⦯'  => '&angmsdah;',
        '⦰'  => '&bemptyv;',
        '⦱'  => '&demptyv;',
        '⦲'  => '&cemptyv;',
        '⦳'  => '&raemptyv;',
        '⦴'  => '&laemptyv;',
        '⦵'  => '&ohbar;',
        '⦶'  => '&omid;',
        '⦷'  => '&opar;',
        '⦹'  => '&operp;',
        '⦻'  => '&olcross;',
        '⦼'  => '&odsold;',
        '⦾'  => '&olcir;',
        '⦿'  => '&ofcir;',
        '⧀'  => '&olt;',
        '⧁'  => '&ogt;',
        '⧂'  => '&cirscir;',
        '⧃'  => '&cirE;',
        '⧄'  => '&solb;',
        '⧅'  => '&bsolb;',
        '⧉'  => '&boxbox;',
        '⧍'  => '&trisb;',
        '⧎'  => '&rtriltri;',
        '⧏'  => '&LeftTriangleBar;',
        '⧏̸' => '&NotLeftTriangleBar;',
        '⧐'  => '&RightTriangleBar;',
        '⧐̸' => '&NotRightTriangleBar;',
        '⧜'  => '&iinfin;',
        '⧝'  => '&infintie;',
        '⧞'  => '&nvinfin;',
        '⧣'  => '&eparsl;',
        '⧤'  => '&smeparsl;',
        '⧥'  => '&eqvparsl;',
        '⧫'  => '&lozf;',
        '⧴'  => '&RuleDelayed;',
        '⧶'  => '&dsol;',
        '⨀'  => '&xodot;',
        '⨁'  => '&bigoplus;',
        '⨂'  => '&bigotimes;',
        '⨄'  => '&biguplus;',
        '⨆'  => '&bigsqcup;',
        '⨌'  => '&iiiint;',
        '⨍'  => '&fpartint;',
        '⨐'  => '&cirfnint;',
        '⨑'  => '&awint;',
        '⨒'  => '&rppolint;',
        '⨓'  => '&scpolint;',
        '⨔'  => '&npolint;',
        '⨕'  => '&pointint;',
        '⨖'  => '&quatint;',
        '⨗'  => '&intlarhk;',
        '⨢'  => '&pluscir;',
        '⨣'  => '&plusacir;',
        '⨤'  => '&simplus;',
        '⨥'  => '&plusdu;',
        '⨦'  => '&plussim;',
        '⨧'  => '&plustwo;',
        '⨩'  => '&mcomma;',
        '⨪'  => '&minusdu;',
        '⨭'  => '&loplus;',
        '⨮'  => '&roplus;',
        '⨯'  => '&Cross;',
        '⨰'  => '&timesd;',
        '⨱'  => '&timesbar;',
        '⨳'  => '&smashp;',
        '⨴'  => '&lotimes;',
        '⨵'  => '&rotimes;',
        '⨶'  => '&otimesas;',
        '⨷'  => '&Otimes;',
        '⨸'  => '&odiv;',
        '⨹'  => '&triplus;',
        '⨺'  => '&triminus;',
        '⨻'  => '&tritime;',
        '⨼'  => '&iprod;',
        '⨿'  => '&amalg;',
        '⩀'  => '&capdot;',
        '⩂'  => '&ncup;',
        '⩃'  => '&ncap;',
        '⩄'  => '&capand;',
        '⩅'  => '&cupor;',
        '⩆'  => '&cupcap;',
        '⩇'  => '&capcup;',
        '⩈'  => '&cupbrcap;',
        '⩉'  => '&capbrcup;',
        '⩊'  => '&cupcup;',
        '⩋'  => '&capcap;',
        '⩌'  => '&ccups;',
        '⩍'  => '&ccaps;',
        '⩐'  => '&ccupssm;',
        '⩓'  => '&And;',
        '⩔'  => '&Or;',
        '⩕'  => '&andand;',
        '⩖'  => '&oror;',
        '⩗'  => '&orslope;',
        '⩘'  => '&andslope;',
        '⩚'  => '&andv;',
        '⩛'  => '&orv;',
        '⩜'  => '&andd;',
        '⩝'  => '&ord;',
        '⩟'  => '&wedbar;',
        '⩦'  => '&sdote;',
        '⩪'  => '&simdot;',
        '⩭'  => '&congdot;',
        '⩭̸' => '&ncongdot;',
        '⩮'  => '&easter;',
        '⩯'  => '&apacir;',
        '⩰'  => '&apE;',
        '⩰̸' => '&napE;',
        '⩱'  => '&eplus;',
        '⩲'  => '&pluse;',
        '⩳'  => '&Esim;',
        '⩴'  => '&Colone;',
        '⩵'  => '&Equal;',
        '⩷'  => '&ddotseq;',
        '⩸'  => '&equivDD;',
        '⩹'  => '&ltcir;',
        '⩺'  => '&gtcir;',
        '⩻'  => '&ltquest;',
        '⩼'  => '&gtquest;',
        '⩽'  => '&les;',
        '⩽̸' => '&nles;',
        '⩾'  => '&ges;',
        '⩾̸' => '&nges;',
        '⩿'  => '&lesdot;',
        '⪀'  => '&gesdot;',
        '⪁'  => '&lesdoto;',
        '⪂'  => '&gesdoto;',
        '⪃'  => '&lesdotor;',
        '⪄'  => '&gesdotol;',
        '⪅'  => '&lap;',
        '⪆'  => '&gap;',
        '⪇'  => '&lne;',
        '⪈'  => '&gne;',
        '⪉'  => '&lnap;',
        '⪊'  => '&gnap;',
        '⪋'  => '&lesseqqgtr;',
        '⪌'  => '&gEl;',
        '⪍'  => '&lsime;',
        '⪎'  => '&gsime;',
        '⪏'  => '&lsimg;',
        '⪐'  => '&gsiml;',
        '⪑'  => '&lgE;',
        '⪒'  => '&glE;',
        '⪓'  => '&lesges;',
        '⪔'  => '&gesles;',
        '⪕'  => '&els;',
        '⪖'  => '&egs;',
        '⪗'  => '&elsdot;',
        '⪘'  => '&egsdot;',
        '⪙'  => '&el;',
        '⪚'  => '&eg;',
        '⪝'  => '&siml;',
        '⪞'  => '&simg;',
        '⪟'  => '&simlE;',
        '⪠'  => '&simgE;',
        '⪡'  => '&LessLess;',
        '⪡̸' => '&NotNestedLessLess;',
        '⪢'  => '&GreaterGreater;',
        '⪢̸' => '&NotNestedGreaterGreater;',
        '⪤'  => '&glj;',
        '⪥'  => '&gla;',
        '⪦'  => '&ltcc;',
        '⪧'  => '&gtcc;',
        '⪨'  => '&lescc;',
        '⪩'  => '&gescc;',
        '⪪'  => '&smt;',
        '⪫'  => '&lat;',
        '⪬'  => '&smte;',
        '⪬︀' => '&smtes;',
        '⪭'  => '&late;',
        '⪭︀' => '&lates;',
        '⪮'  => '&bumpE;',
        '⪯'  => '&preceq;',
        '⪯̸' => '&NotPrecedesEqual;',
        '⪰'  => '&SucceedsEqual;',
        '⪰̸' => '&NotSucceedsEqual;',
        '⪳'  => '&prE;',
        '⪴'  => '&scE;',
        '⪵'  => '&precneqq;',
        '⪶'  => '&scnE;',
        '⪷'  => '&precapprox;',
        '⪸'  => '&succapprox;',
        '⪹'  => '&precnapprox;',
        '⪺'  => '&succnapprox;',
        '⪻'  => '&Pr;',
        '⪼'  => '&Sc;',
        '⪽'  => '&subdot;',
        '⪾'  => '&supdot;',
        '⪿'  => '&subplus;',
        '⫀'  => '&supplus;',
        '⫁'  => '&submult;',
        '⫂'  => '&supmult;',
        '⫃'  => '&subedot;',
        '⫄'  => '&supedot;',
        '⫅'  => '&subE;',
        '⫅̸' => '&nsubE;',
        '⫆'  => '&supseteqq;',
        '⫆̸' => '&nsupseteqq;',
        '⫇'  => '&subsim;',
        '⫈'  => '&supsim;',
        '⫋'  => '&subsetneqq;',
        '⫋︀' => '&vsubnE;',
        '⫌'  => '&supnE;',
        '⫌︀' => '&varsupsetneqq;',
        '⫏'  => '&csub;',
        '⫐'  => '&csup;',
        '⫑'  => '&csube;',
        '⫒'  => '&csupe;',
        '⫓'  => '&subsup;',
        '⫔'  => '&supsub;',
        '⫕'  => '&subsub;',
        '⫖'  => '&supsup;',
        '⫗'  => '&suphsub;',
        '⫘'  => '&supdsub;',
        '⫙'  => '&forkv;',
        '⫚'  => '&topfork;',
        '⫛'  => '&mlcp;',
        '⫤'  => '&Dashv;',
        '⫦'  => '&Vdashl;',
        '⫧'  => '&Barv;',
        '⫨'  => '&vBar;',
        '⫩'  => '&vBarv;',
        '⫫'  => '&Vbar;',
        '⫬'  => '&Not;',
        '⫭'  => '&bNot;',
        '⫮'  => '&rnmid;',
        '⫯'  => '&cirmid;',
        '⫰'  => '&midcir;',
        '⫱'  => '&topcir;',
        '⫲'  => '&nhpar;',
        '⫳'  => '&parsim;',
        '⫽'  => '&parsl;',
        '⫽⃥' => '&nparsl;',
        'ﬀ'  => '&fflig;',
        'ﬁ'  => '&filig;',
        'ﬂ'  => '&fllig;',
        'ﬃ'  => '&ffilig;',
        'ﬄ'  => '&ffllig;',
        '𝒜' => '&Ascr;',
        '𝒞' => '&Cscr;',
        '𝒟' => '&Dscr;',
        '𝒢' => '&Gscr;',
        '𝒥' => '&Jscr;',
        '𝒦' => '&Kscr;',
        '𝒩' => '&Nscr;',
        '𝒪' => '&Oscr;',
        '𝒫' => '&Pscr;',
        '𝒬' => '&Qscr;',
        '𝒮' => '&Sscr;',
        '𝒯' => '&Tscr;',
        '𝒰' => '&Uscr;',
        '𝒱' => '&Vscr;',
        '𝒲' => '&Wscr;',
        '𝒳' => '&Xscr;',
        '𝒴' => '&Yscr;',
        '𝒵' => '&Zscr;',
        '𝒶' => '&ascr;',
        '𝒷' => '&bscr;',
        '𝒸' => '&cscr;',
        '𝒹' => '&dscr;',
        '𝒻' => '&fscr;',
        '𝒽' => '&hscr;',
        '𝒾' => '&iscr;',
        '𝒿' => '&jscr;',
        '𝓀' => '&kscr;',
        '𝓁' => '&lscr;',
        '𝓂' => '&mscr;',
        '𝓃' => '&nscr;',
        '𝓅' => '&pscr;',
        '𝓆' => '&qscr;',
        '𝓇' => '&rscr;',
        '𝓈' => '&sscr;',
        '𝓉' => '&tscr;',
        '𝓊' => '&uscr;',
        '𝓋' => '&vscr;',
        '𝓌' => '&wscr;',
        '𝓍' => '&xscr;',
        '𝓎' => '&yscr;',
        '𝓏' => '&zscr;',
        '𝔄' => '&Afr;',
        '𝔅' => '&Bfr;',
        '𝔇' => '&Dfr;',
        '𝔈' => '&Efr;',
        '𝔉' => '&Ffr;',
        '𝔊' => '&Gfr;',
        '𝔍' => '&Jfr;',
        '𝔎' => '&Kfr;',
        '𝔏' => '&Lfr;',
        '𝔐' => '&Mfr;',
        '𝔑' => '&Nfr;',
        '𝔒' => '&Ofr;',
        '𝔓' => '&Pfr;',
        '𝔔' => '&Qfr;',
        '𝔖' => '&Sfr;',
        '𝔗' => '&Tfr;',
        '𝔘' => '&Ufr;',
        '𝔙' => '&Vfr;',
        '𝔚' => '&Wfr;',
        '𝔛' => '&Xfr;',
        '𝔜' => '&Yfr;',
        '𝔞' => '&afr;',
        '𝔟' => '&bfr;',
        '𝔠' => '&cfr;',
        '𝔡' => '&dfr;',
        '𝔢' => '&efr;',
        '𝔣' => '&ffr;',
        '𝔤' => '&gfr;',
        '𝔥' => '&hfr;',
        '𝔦' => '&ifr;',
        '𝔧' => '&jfr;',
        '𝔨' => '&kfr;',
        '𝔩' => '&lfr;',
        '𝔪' => '&mfr;',
        '𝔫' => '&nfr;',
        '𝔬' => '&ofr;',
        '𝔭' => '&pfr;',
        '𝔮' => '&qfr;',
        '𝔯' => '&rfr;',
        '𝔰' => '&sfr;',
        '𝔱' => '&tfr;',
        '𝔲' => '&ufr;',
        '𝔳' => '&vfr;',
        '𝔴' => '&wfr;',
        '𝔵' => '&xfr;',
        '𝔶' => '&yfr;',
        '𝔷' => '&zfr;',
        '𝔸' => '&Aopf;',
        '𝔹' => '&Bopf;',
        '𝔻' => '&Dopf;',
        '𝔼' => '&Eopf;',
        '𝔽' => '&Fopf;',
        '𝔾' => '&Gopf;',
        '𝕀' => '&Iopf;',
        '𝕁' => '&Jopf;',
        '𝕂' => '&Kopf;',
        '𝕃' => '&Lopf;',
        '𝕄' => '&Mopf;',
        '𝕆' => '&Oopf;',
        '𝕊' => '&Sopf;',
        '𝕋' => '&Topf;',
        '𝕌' => '&Uopf;',
        '𝕍' => '&Vopf;',
        '𝕎' => '&Wopf;',
        '𝕏' => '&Xopf;',
        '𝕐' => '&Yopf;',
        '𝕒' => '&aopf;',
        '𝕓' => '&bopf;',
        '𝕔' => '&copf;',
        '𝕕' => '&dopf;',
        '𝕖' => '&eopf;',
        '𝕗' => '&fopf;',
        '𝕘' => '&gopf;',
        '𝕙' => '&hopf;',
        '𝕚' => '&iopf;',
        '𝕛' => '&jopf;',
        '𝕜' => '&kopf;',
        '𝕝' => '&lopf;',
        '𝕞' => '&mopf;',
        '𝕟' => '&nopf;',
        '𝕠' => '&oopf;',
        '𝕡' => '&popf;',
        '𝕢' => '&qopf;',
        '𝕣' => '&ropf;',
        '𝕤' => '&sopf;',
        '𝕥' => '&topf;',
        '𝕦' => '&uopf;',
        '𝕧' => '&vopf;',
        '𝕨' => '&wopf;',
        '𝕩' => '&xopf;',
        '𝕪' => '&yopf;',
        '𝕫' => '&zopf;',
    );

    public $digit_map = [
        "\x20",
        "\x21",
        "\x22",
        "\x23",
        "\x24",
        "\x25",
        "\x26",
        "\x27",
        "\x28",
        "\x29",
        "\x2a",
        "\x2b",
        "\x2c",
        "\x2d",
        "\x2e",
        "\x2f",
        "\x30",
        "\x31",
        "\x32",
        "\x33",
        "\x34",
        "\x35",
        "\x36",
        "\x37",
        "\x3a",
        "\x3f",
        "\x3d",
        "\x5f",
    ];

    public $digit_map_255 = [
        "\x00" => 0,
        "\x01" => 1,
        "\x02" => 2,
        "\x03" => 3,
        "\x04" => 4,
        "\x05" => 5,
        "\x06" => 6,
        "\x07" => 7,
        "\x08" => 8,
        "\x09" => 9,
        "\x0A" => 10,
        "\x0B" => 11,
        "\x0C" => 12,
        "\x0D" => 13,
        "\x0E" => 14,
        "\x0F" => 15,
        "\x10" => 16,
        "\x11" => 17,
        "\x12" => 18,
        "\x13" => 19,
        "\x14" => 20,
        "\x15" => 21,
        "\x16" => 22,
        "\x17" => 23,
        "\x18" => 24,
        "\x19" => 25,
        "\x1A" => 26,
        "\x1B" => 27,
        "\x1C" => 28,
        "\x1D" => 29,
        "\x1E" => 30,
        "\x1F" => 31,
        "\x20" => 32,
        "\x21" => 33,
        "\x22" => 34,
        "\x23" => 35,
        "\x24" => 36,
        "\x25" => 37,
        "\x26" => 38,
        "\x27" => 39,
        "\x28" => 40,
        "\x29" => 41,
        "\x2A" => 42,
        "\x2B" => 43,
        "\x2C" => 44,
        "\x2D" => 45,
        "\x2E" => 46,
        "\x2F" => 47,
        "\x30" => 48,
        "\x31" => 49,
        "\x32" => 50,
        "\x33" => 51,
        "\x34" => 52,
        "\x35" => 53,
        "\x36" => 54,
        "\x37" => 55,
        "\x38" => 56,
        "\x39" => 57,
        "\x3A" => 58,
        "\x3B" => 59,
        "\x3C" => 60,
        "\x3D" => 61,
        "\x3E" => 62,
        "\x3F" => 63,
        "\x40" => 64,
        "\x41" => 65,
        "\x42" => 66,
        "\x43" => 67,
        "\x44" => 68,
        "\x45" => 69,
        "\x46" => 70,
        "\x47" => 71,
        "\x48" => 72,
        "\x49" => 73,
        "\x4A" => 74,
        "\x4B" => 75,
        "\x4C" => 76,
        "\x4D" => 77,
        "\x4E" => 78,
        "\x4F" => 79,
        "\x50" => 80,
        "\x51" => 81,
        "\x52" => 82,
        "\x53" => 83,
        "\x54" => 84,
        "\x55" => 85,
        "\x56" => 86,
        "\x57" => 87,
        "\x58" => 88,
        "\x59" => 89,
        "\x5A" => 90,
        "\x5B" => 91,
        "\x5C" => 92,
        "\x5D" => 93,
        "\x5E" => 94,
        "\x5F" => 95,
        "\x60" => 96,
        "\x61" => 97,
        "\x62" => 98,
        "\x63" => 99,
        "\x64" => 100,
        "\x65" => 101,
        "\x66" => 102,
        "\x67" => 103,
        "\x68" => 104,
        "\x69" => 105,
        "\x6A" => 106,
        "\x6B" => 107,
        "\x6C" => 108,
        "\x6D" => 109,
        "\x6E" => 110,
        "\x6F" => 111,
        "\x70" => 112,
        "\x71" => 113,
        "\x72" => 114,
        "\x73" => 115,
        "\x74" => 116,
        "\x75" => 117,
        "\x76" => 118,
        "\x77" => 119,
        "\x78" => 120,
        "\x79" => 121,
        "\x7A" => 122,
        "\x7B" => 123,
        "\x7C" => 124,
        "\x7D" => 125,
        "\x7E" => 126,
        "\x7F" => 127,
        "\x80" => 128,
        "\x81" => 129,
        "\x82" => 130,
        "\x83" => 131,
        "\x84" => 132,
        "\x85" => 133,
        "\x86" => 134,
        "\x87" => 135,
        "\x88" => 136,
        "\x89" => 137,
        "\x8A" => 138,
        "\x8B" => 139,
        "\x8C" => 140,
        "\x8D" => 141,
        "\x8E" => 142,
        "\x8F" => 143,
        "\x90" => 144,
        "\x91" => 145,
        "\x92" => 146,
        "\x93" => 147,
        "\x94" => 148,
        "\x95" => 149,
        "\x96" => 150,
        "\x97" => 151,
        "\x98" => 152,
        "\x99" => 153,
        "\x9A" => 154,
        "\x9B" => 155,
        "\x9C" => 156,
        "\x9D" => 157,
        "\x9E" => 158,
        "\x9F" => 159,
        "\xA0" => 160,
        "\xA1" => 161,
        "\xA2" => 162,
        "\xA3" => 163,
        "\xA4" => 164,
        "\xA5" => 165,
        "\xA6" => 166,
        "\xA7" => 167,
        "\xA8" => 168,
        "\xA9" => 169,
        "\xAA" => 170,
        "\xAB" => 171,
        "\xAC" => 172,
        "\xAD" => 173,
        "\xAE" => 174,
        "\xAF" => 175,
        "\xB0" => 176,
        "\xB1" => 177,
        "\xB2" => 178,
        "\xB3" => 179,
        "\xB4" => 180,
        "\xB5" => 181,
        "\xB6" => 182,
        "\xB7" => 183,
        "\xB8" => 184,
        "\xB9" => 185,
        "\xBA" => 186,
        "\xBB" => 187,
        "\xBC" => 188,
        "\xBD" => 189,
        "\xBE" => 190,
        "\xBF" => 191,
        "\xC0" => 192,
        "\xC1" => 193,
        "\xC2" => 194,
        "\xC3" => 195,
        "\xC4" => 196,
        "\xC5" => 197,
        "\xC6" => 198,
        "\xC7" => 199,
        "\xC8" => 200,
        "\xC9" => 201,
        "\xCA" => 202,
        "\xCB" => 203,
        "\xCC" => 204,
        "\xCD" => 205,
        "\xCE" => 206,
        "\xCF" => 207,
        "\xD0" => 208,
        "\xD1" => 209,
        "\xD2" => 210,
        "\xD3" => 211,
        "\xD4" => 212,
        "\xD5" => 213,
        "\xD6" => 214,
        "\xD7" => 215,
        "\xD8" => 216,
        "\xD9" => 217,
        "\xDA" => 218,
        "\xDB" => 219,
        "\xDC" => 220,
        "\xDD" => 221,
        "\xDE" => 222,
        "\xDF" => 223,
        "\xE0" => 224,
        "\xE1" => 225,
        "\xE2" => 226,
        "\xE3" => 227,
        "\xE4" => 228,
        "\xE5" => 229,
        "\xE6" => 230,
        "\xE7" => 231,
        "\xE8" => 232,
        "\xE9" => 233,
        "\xEA" => 234,
        "\xEB" => 235,
        "\xEC" => 236,
        "\xED" => 237,
        "\xEE" => 238,
        "\xEF" => 239,
        "\xF0" => 240,
        "\xF1" => 241,
        "\xF2" => 242,
        "\xF3" => 243,
        "\xF4" => 244,
        "\xF5" => 245,
        "\xF6" => 246,
        "\xF7" => 247,
        "\xF8" => 248,
        "\xF9" => 249,
        "\xFA" => 250,
        "\xFB" => 251,
        "\xFC" => 252,
        "\xFD" => 253,
        "\xFE" => 254,
        "\xFF" => 255,
    ];

    public $u_alphas = [
        "\x4c",
        "\x49",
        "\x43",
        "\x45",
        "\x4e",
        "\x53",
        "\x70",
        "\x71",
        "\x72",
        "\x73",
        "\x74",
        "\x75",
        "\x76",
        "\x77",
        "\x78",
        "\x79",
        "\x7a",
        "\x52",
        "\x56",
        "\x41",
        "\x4d",
    ];

    public $isoprophics = [
        'ANSI_X3.4-1968',
        'ANSI_X3.4-1986',
        'ASCII',
        'CP367',
        'IBM367',
        'ISO-IR-6',
        'ISO646-US',
        'ISO_646.IRV:1991',
        'US',
        'US-ASCII',
        'CSASCII',
        'UTF-8',
        'ISO-10646-UCS-2',
        'UCS-2',
        'CSUNICODE',
        'UCS-2BE',
        'UNICODE-1-1',
        'UNICODEBIG',
        'CSUNICODE11',
        'UCS-2LE',
        'UNICODELITTLE',
        'ISO-10646-UCS-4',
        'UCS-4',
        'CSUCS4',
        'UCS-4BE',
        'UCS-4LE',
        'UTF-16',
        'UTF-16BE',
        'UTF-16LE',
        'UTF-32',
        'UTF-32BE',
        'UTF-32LE',
        'UNICODE-1-1-UTF-7',
        'UTF-7',
        'CSUNICODE11UTF7',
        'UCS-2-INTERNAL',
        'UCS-2-SWAPPED',
        'UCS-4-INTERNAL',
        'UCS-4-SWAPPED',
        'C99',
        'JAVA',
        'CP819',
        'IBM819',
        'ISO-8859-1',
        'ISO-IR-100',
        'ISO8859-1',
        'ISO_8859-1',
        'ISO_8859-1:1987',
        'L1',
        'LATIN1',
        'CSISOLATIN1',
        'ISO-8859-2',
        'ISO-IR-101',
        'ISO8859-2',
        'ISO_8859-2',
        'ISO_8859-2:1987',
        'L2',
        'LATIN2',
        'CSISOLATIN2',
        'ISO-8859-3',
        'ISO-IR-109',
        'ISO8859-3',
        'ISO_8859-3',
        'ISO_8859-3:1988',
        'L3',
        'LATIN3',
        'CSISOLATIN3',
        'ISO-8859-4',
        'ISO-IR-110',
        'ISO8859-4',
        'ISO_8859-4',
        'ISO_8859-4:1988',
        'L4',
        'LATIN4',
        'CSISOLATIN4',
        'CYRILLIC',
        'ISO-8859-5',
        'ISO-IR-144',
        'ISO8859-5',
        'ISO_8859-5',
        'ISO_8859-5:1988',
        'CSISOLATINCYRILLIC',
        'ARABIC',
        'ASMO-708',
        'ECMA-114',
        'ISO-8859-6',
        'ISO-IR-127',
        'ISO8859-6',
        'ISO_8859-6',
        'ISO_8859-6:1987',
        'CSISOLATINARABIC',
        'ECMA-118',
        'ELOT_928',
        'GREEK',
        'GREEK8',
        'ISO-8859-7',
        'ISO-IR-126',
        'ISO8859-7',
        'ISO_8859-7',
        'ISO_8859-7:1987',
        'ISO_8859-7:2003',
        'CSISOLATINGREEK',
        'HEBREW',
        'ISO-8859-8',
        'ISO-IR-138',
        'ISO8859-8',
        'ISO_8859-8',
        'ISO_8859-8:1988',
        'CSISOLATINHEBREW',
        'ISO-8859-9',
        'ISO-IR-148',
        'ISO8859-9',
        'ISO_8859-9',
        'ISO_8859-9:1989',
        'L5',
        'LATIN5',
        'CSISOLATIN5',
        'ISO-8859-10',
        'ISO-IR-157',
        'ISO8859-10',
        'ISO_8859-10',
        'ISO_8859-10:1992',
        'L6',
        'LATIN6',
        'CSISOLATIN6',
        'ISO-8859-11',
        'ISO8859-11',
        'ISO_8859-11',
        'ISO-8859-13',
        'ISO-IR-179',
        'ISO8859-13',
        'ISO_8859-13',
        'L7',
        'LATIN7',
        'ISO-8859-14',
        'ISO-CELTIC',
        'ISO-IR-199',
        'ISO8859-14',
        'ISO_8859-14',
        'ISO_8859-14:1998',
        'L8',
        'LATIN8',
        'ISO-8859-15',
        'ISO-IR-203',
        'ISO8859-15',
        'ISO_8859-15',
        'ISO_8859-15:1998',
        'LATIN-9',
        'ISO-8859-16',
        'ISO-IR-226',
        'ISO8859-16',
        'ISO_8859-16',
        'ISO_8859-16:2001',
        'L10',
        'LATIN10',
        'KOI8-R',
        'CSKOI8R',
        'KOI8-U',
        'KOI8-RU',
        'CP1250',
        'MS-EE',
        'WINDOWS-1250',
        'CP1251',
        'MS-CYRL',
        'WINDOWS-1251',
        'CP1252',
        'MS-ANSI',
        'WINDOWS-1252',
        'CP1253',
        'MS-GREEK',
        'WINDOWS-1253',
        'CP1254',
        'MS-TURK',
        'WINDOWS-1254',
        'CP1255',
        'MS-HEBR',
        'WINDOWS-1255',
        'CP1256',
        'MS-ARAB',
        'WINDOWS-1256',
        'CP1257',
        'WINBALTRIM',
        'WINDOWS-1257',
        'CP1258',
        'WINDOWS-1258',
        '850',
        'CP850',
        'IBM850',
        'CSPC850MULTILINGUAL',
        '862',
        'CP862',
        'IBM862',
        'CSPC862LATINHEBREW',
        '866',
        'CP866',
        'IBM866',
        'CSIBM866',
        'MAC',
        'MACINTOSH',
        'MACROMAN',
        'CSMACINTOSH',
        'MACCENTRALEUROPE',
        'MACICELAND',
        'MACCROATIAN',
        'MACROMANIA',
        'MACCYRILLIC',
        'MACUKRAINE',
        'MACGREEK',
        'MACTURKISH',
        'MACHEBREW',
        'MACARABIC',
        'MACTHAI',
        'HP-ROMAN8',
        'R8',
        'ROMAN8',
        'CSHPROMAN8',
        'NEXTSTEP',
        'ARMSCII-8',
        'GEORGIAN-ACADEMY',
        'GEORGIAN-PS',
        'KOI8-T',
        'CP154',
        'CYRILLIC-ASIAN',
        'PT154',
        'PTCP154',
        'CSPTCP154',
        'KZ-1048',
        'RK1048',
        'STRK1048-2002',
        'CSKZ1048',
        'MULELAO-1',
        'CP1133',
        'IBM-CP1133',
        'ISO-IR-166',
        'TIS-620',
        'TIS620',
        'TIS620-0',
        'TIS620.2529-1',
        'TIS620.2533-0',
        'TIS620.2533-1',
        'CP874',
        'WINDOWS-874',
        'VISCII',
        'VISCII1.1-1',
        'CSVISCII',
        'TCVN',
        'TCVN-5712',
        'TCVN5712-1',
        'TCVN5712-1:1993',
        'ISO-IR-14',
        'ISO646-JP',
        'JIS_C6220-1969-RO',
        'JP',
        'CSISO14JISC6220RO',
        'JISX0201-1976',
        'JIS_X0201',
        'X0201',
        'CSHALFWIDTHKATAKANA',
        'ISO-IR-87',
        'JIS0208',
        'JIS_C6226-1983',
        'JIS_X0208',
        'JIS_X0208-1983',
        'JIS_X0208-1990',
        'X0208',
        'CSISO87JISX0208',
        'ISO-IR-159',
        'JIS_X0212',
        'JIS_X0212-1990',
        'JIS_X0212.1990-0',
        'X0212',
        'CSISO159JISX02121990',
        'CN',
        'GB_1988-80',
        'ISO-IR-57',
        'ISO646-CN',
        'CSISO57GB1988',
        'CHINESE',
        'GB_2312-80',
        'ISO-IR-58',
        'CSISO58GB231280',
        'CN-GB-ISOIR165',
        'ISO-IR-165',
        'ISO-IR-149',
        'KOREAN',
        'KSC_5601',
        'KS_C_5601-1987',
        'KS_C_5601-1989',
        'CSKSC56011987',
        'EUC-JP',
        'EUCJP',
        'EXTENDED_UNIX_CODE_PACKED_FORMAT_FOR_JAPANESE',
        'CSEUCPKDFMTJAPANESE',
        'MS_KANJI',
        'SHIFT-JIS',
        'SHIFT_JIS',
        'SJIS',
        'CSSHIFTJIS',
        'CP932',
        'ISO-2022-JP',
        'CSISO2022JP',
        'ISO-2022-JP-1',
        'ISO-2022-JP-2',
        'CSISO2022JP2',
        'CN-GB',
        'EUC-CN',
        'EUCCN',
        'GB2312',
        'CSGB2312',
        'GBK',
        'CP936',
        'MS936',
        'WINDOWS-936',
        'GB18030',
        'ISO-2022-CN',
        'CSISO2022CN',
        'ISO-2022-CN-EXT',
        'HZ',
        'HZ-GB-2312',
        'EUC-TW',
        'EUCTW',
        'CSEUCTW',
        'BIG-5',
        'BIG-FIVE',
        'BIG5',
        'BIGFIVE',
        'CN-BIG5',
        'CSBIG5',
        'CP950',
        'BIG5-HKSCS:1999',
        'BIG5-HKSCS:2001',
        'BIG5-HKSCS',
        'BIG5-HKSCS:2004',
        'BIG5HKSCS',
        'EUC-KR',
        'EUCKR',
        'CSEUCKR',
        'CP949',
        'UHC',
        'CP1361',
        'JOHAB',
        'ISO-2022-KR',
        'CSISO2022KR',
        'CP856',
        'CP922',
        'CP943',
        'CP1046',
        'CP1124',
        'CP1129',
        'CP1161',
        'IBM-1161',
        'IBM1161',
        'CSIBM1161',
        'CP1162',
        'IBM-1162',
        'IBM1162',
        'CSIBM1162',
        'CP1163',
        'IBM-1163',
        'IBM1163',
        'CSIBM1163',
        'DEC-KANJI',
        'DEC-HANYU',
        '437',
        'CP437',
        'IBM437',
        'CSPC8CODEPAGE437',
        'CP737',
        'CP775',
        'IBM775',
        'CSPC775BALTIC',
        '852',
        'CP852',
        'IBM852',
        'CSPCP852',
        'CP853',
        '855',
        'CP855',
        'IBM855',
        'CSIBM855',
        '857',
        'CP857',
        'IBM857',
        'CSIBM857',
        'CP858',
        '860',
        'CP860',
        'IBM860',
        'CSIBM860',
        '861',
        'CP-IS',
        'CP861',
        'IBM861',
        'CSIBM861',
        '863',
        'CP863',
        'IBM863',
        'CSIBM863',
        'CP864',
        'IBM864',
        'CSIBM864',
        '865',
        'CP865',
        'IBM865',
        'CSIBM865',
        '869',
        'CP-GR',
        'CP869',
        'IBM869',
        'CSIBM869',
        'CP1125',
        'EUC-JISX0213',
        'SHIFT_JISX0213',
        'ISO-2022-JP-3',
        'BIG5-2003',
        'ISO-IR-230',
        'TDS565',
        'ATARI',
        'ATARIST',
        'RISCOS-LATIN1',
    ];

    public $event_map = array(
        'FSCommand',
        'onAbort',
        'onActivate',
        'onAttribute',
        'onAfterPrint',
        'onAfterScriptExecute',
        'onAfterUpdate',
        'onAnimationEnd',
        'onAnimationIteration',
        'onAnimationStart',
        'onAriaRequest',
        'onAutoComplete',
        'onAutoCompleteError',
        'onBeforeActivate',
        'onBeforeCopy',
        'onBeforeCut',
        'onBeforeDeactivate',
        'onBeforeEditFocus',
        'onBeforePaste',
        'onBeforePrint',
        'onBeforeScriptExecute',
        'onBeforeUnload',
        'onBeforeUpdate',
        'onBegin',
        'onBlur',
        'onBounce',
        'onCancel',
        'onCanPlay',
        'onCanPlayThrough',
        'onCellChange',
        'onChange',
        'onClick',
        'onClose',
        'onCommand',
        'onCompassNeedsCalibration',
        'onContextMenu',
        'onControlSelect',
        'onCopy',
        'onCueChange',
        'onCut',
        'onDataAvailable',
        'onDataSetChanged',
        'onDataSetComplete',
        'onDblClick',
        'onDeactivate',
        'onDeviceLight',
        'onDeviceMotion',
        'onDeviceOrientation',
        'onDeviceProximity',
        'onDrag',
        'onDragDrop',
        'onDragEnd',
        'onDragEnter',
        'onDragLeave',
        'onDragOver',
        'onDragStart',
        'onDrop',
        'onDurationChange',
        'onEmptied',
        'onEnd',
        'onEnded',
        'onError',
        'onErrorUpdate',
        'onExit',
        'onFilterChange',
        'onFinish',
        'onFocus',
        'onFocusIn',
        'onFocusOut',
        'onFormChange',
        'onFormInput',
        'onFullScreenChange',
        'onFullScreenError',
        'onGotPointerCapture',
        'onHashChange',
        'onHelp',
        'onInput',
        'onInvalid',
        'onKeyDown',
        'onKeyPress',
        'onKeyUp',
        'onLanguageChange',
        'onLayoutComplete',
        'onLoad',
        'onLoadedData',
        'onLoadedMetaData',
        'onLoadStart',
        'onLoseCapture',
        'onLostPointerCapture',
        'onMediaComplete',
        'onMediaError',
        'onMessage',
        'onMouseDown',
        'onMouseEnter',
        'onMouseLeave',
        'onMouseMove',
        'onMouseOut',
        'onMouseOver',
        'onMouseUp',
        'onMouseWheel',
        'onMove',
        'onMoveEnd',
        'onMoveStart',
        'onMozFullScreenChange',
        'onMozFullScreenError',
        'onMozPointerLockChange',
        'onMozPointerLockError',
        'onMsContentZoom',
        'onMsFullScreenChange',
        'onMsFullScreenError',
        'onMsGestureChange',
        'onMsGestureDoubleTap',
        'onMsGestureEnd',
        'onMsGestureHold',
        'onMsGestureStart',
        'onMsGestureTap',
        'onMsGotPointerCapture',
        'onMsInertiaStart',
        'onMsLostPointerCapture',
        'onMsManipulationStateChanged',
        'onMsPointerCancel',
        'onMsPointerDown',
        'onMsPointerEnter',
        'onMsPointerLeave',
        'onMsPointerMove',
        'onMsPointerOut',
        'onMsPointerOver',
        'onMsPointerUp',
        'onMsSiteModeJumpListItemRemoved',
        'onMsThumbnailClick',
        'onOffline',
        'onOnline',
        'onOutOfSync',
        'onPage',
        'onPageHide',
        'onPageShow',
        'onPaste',
        'onPause',
        'onPlay',
        'onPlaying',
        'onPointerCancel',
        'onPointerDown',
        'onPointerEnter',
        'onPointerLeave',
        'onPointerLockChange',
        'onPointerLockError',
        'onPointerMove',
        'onPointerOut',
        'onPointerOver',
        'onPointerUp',
        'onPopState',
        'onProgress',
        'onPropertyChange',
        'onRateChange',
        'onReadyStateChange',
        'onReceived',
        'onRepeat',
        'onReset',
        'onResize',
        'onResizeEnd',
        'onResizeStart',
        'onResume',
        'onReverse',
        'onRowDelete',
        'onRowEnter',
        'onRowExit',
        'onRowInserted',
        'onRowsDelete',
        'onRowsEnter',
        'onRowsExit',
        'onRowsInserted',
        'onScroll',
        'onSearch',
        'onSeek',
        'onSeeked',
        'onSeeking',
        'onSelect',
        'onSelectionChange',
        'onSelectStart',
        'onStalled',
        'onStorage',
        'onStorageCommit',
        'onStart',
        'onStop',
        'onShow',
        'onSyncRestored',
        'onSubmit',
        'onSuspend',
        'onSynchRestored',
        'onTimeError',
        'onTimeUpdate',
        'onTrackChange',
        'onTransitionEnd',
        'onToggle',
        'onUnload',
        'onURLFlip',
        'onUserProximity',
        'onVolumeChange',
        'onWaiting',
        'onWebKitAnimationEnd',
        'onWebKitAnimationIteration',
        'onWebKitAnimationStart',
        'onWebKitFullScreenChange',
        'onWebKitFullScreenError',
        'onWebKitTransitionEnd',
        'onWheel',
        'seekSegmentTime',
        'userid',
        'datasrc',
        'datafld',
        'dataformatas',
        'ev:handler',
        'ev:event',
        '0;url',
    );
}
